Swap babel-polifill for @babel/polyfill
This is to avoid conflict with nestjs
[Nest] 1   - 07/30/2020, 10:27:51 AM   [ExceptionHandler] Map#toJSON isn't generic +11ms
TypeError: Map#toJSON isn't generic
    at String.toJSON (/opt/app-root/src/repo/node_modules/core-js/modules/_collection-to-json.js:6:38)
    at Function.<anonymous> (/opt/app-root/src/repo/node_modules/core-js/modules/_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at Function.stringify [as default] (/opt/app-root/src/repo/node_modules/fast-safe-stringify/index.js:14:16)
    at ModuleTokenFactory.getDynamicMetadataToken (/opt/app-root/src/repo/node_modules/@nestjs/core/injector/module-token-factory.js:25:44)
    at ModuleTokenFactory.create (/opt/app-root/src/repo/node_modules/@nestjs/core/injector/module-token-factory.js:16:27)
    at ModuleCompiler.compile (/opt/app-root/src/repo/node_modules/@nestjs/core/injector/compiler.js:12:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)